"""Static exporter for converting CodeNeuro dynamic rules into Cursor MDC and Claude.md."""

import re
from pathlib import Path
from typing import List, Optional
from codeneuro.models import Lifecycle, Priority, Rule, RuleStatus


def slugify(text: str) -> str:
    """Convert text to safe lowercase filename slug."""
    text = re.sub(r'[^\w\s-]', '', text).strip().lower()
    return re.sub(r'[-\s]+', '-', text) or "rule"


class RuleExporter:
    """Exports in-memory / database rules into static config files."""

    @staticmethod
    def rule_to_mdc(rule: Rule) -> str:
        """Render a single rule into Cursor .mdc format with YAML frontmatter."""
        globs_str = ", ".join(rule.scope_patterns)
        always_apply = "true" if "**" in rule.scope_patterns and rule.priority == Priority.P0 else "false"

        lines = [
            "---",
            f"description: {rule.title}",
            f"globs: {globs_str}",
            f"alwaysApply: {always_apply}",
            "---",
            "",
            f"# [{rule.priority.value}] {rule.title}",
            f"<!-- Lifecycle: {rule.lifecycle.value} | Created by: {rule.created_by} -->",
            "",
        ]
        for pt in rule.content_points:
            lines.append(f"- {pt}")

        return "\n".join(lines)

    @classmethod
    def export_cursor_rules(
        cls,
        rules: List[Rule],
        out_dir: Path,
        active_task_id: Optional[str] = None
    ) -> List[Path]:
        """Export active rules to .cursor/rules/*.mdc directory."""
        cursor_dir = out_dir / ".cursor" / "rules"
        cursor_dir.mkdir(parents=True, exist_ok=True)

        exported_paths = []
        for r in rules:
            if r.status != RuleStatus.ACTIVE:
                continue
            if r.lifecycle == Lifecycle.SHORT_TERM and active_task_id and r.task_id != active_task_id:
                continue

            slug = f"{r.priority.value.lower()}-{slugify(r.title)[:30]}-{r.id[:8]}.mdc"
            file_path = cursor_dir / slug
            content = cls.rule_to_mdc(r)
            file_path.write_text(content, encoding="utf-8")
            exported_paths.append(file_path)

        return exported_paths

    @classmethod
    def export_claude_md(
        cls,
        rules: List[Rule],
        out_file: Path,
        active_task_id: Optional[str] = None
    ) -> Path:
        """Export active rules into a combined CLAUDE.md / AGENTS.md document."""
        out_file.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Project Cognitive Rules & Scoped Constraints",
            "> Auto-generated by CodeNeuro Hub. Do not edit manually.",
            "",
            "## 🏛️ Persistent Architecture Contracts (P0 / Redlines)",
        ]

        p0_rules = [r for r in rules if r.priority == Priority.P0 and r.status == RuleStatus.ACTIVE]
        for r in p0_rules:
            scopes = ", ".join(f"`{s}`" for s in r.scope_patterns)
            lines.append(f"### [P0] {r.title} (Scopes: {scopes})")
            for pt in r.content_points:
                lines.append(f"- {pt}")
            lines.append("")

        lines.append("## ⚡ Active Iteration Constraints & Guidelines")
        other_rules = [
            r for r in rules
            if r.priority != Priority.P0
            and r.status == RuleStatus.ACTIVE
            and (r.lifecycle == Lifecycle.LONG_TERM or (active_task_id and r.task_id == active_task_id))
        ]
        for r in other_rules:
            scopes = ", ".join(f"`{s}`" for s in r.scope_patterns)
            lines.append(f"### [{r.priority.value}] {r.title} (Scopes: {scopes})")
            for pt in r.content_points:
                lines.append(f"- {pt}")
            lines.append("")

        out_file.write_text("\n".join(lines), encoding="utf-8")
        return out_file
